### ISSUE TITLE
External database

### ISSUE THREAD

**Issue by ValentinPifu** [espocrm/docker#5]
Hello,

We want to migrate our espocrm from standard installation to docker version but I have some questions about this [the default docker-compose it's working fine with mysql container].

1. How can I connect to another mysql server? [not container]
2. Atm in the current server we have a folder mounted from the main storage
[**/var/www/html/epsocrm/data/upload**]
How can I mount this folder directly into the container because we have lots (30k+ documents).

With this config I'm getting **Error 500**.

```
version: '3.1'

services:
  espocrm:
    container_name: espocrm
    image: espocrm/espocrm
    environment:
      ESPOCRM_DATABASE_HOST: 192.168.3.107
      ESPOCRM_DATABASE_NAME: crm
      ESPOCRM_DATABASE_USER: crm
      ESPOCRM_DATABASE_PASSWORD: 123456
      ESPOCRM_ADMIN_USERNAME: admin
      ESPOCRM_ADMIN_PASSWORD: password
      ESPOCRM_SITE_URL: "http://localhost:8080"
    restart: always
    ports:
      - 8282:80
    volumes:
     - ./data:/var/www/html
     - ./docs:/var/www/html/epsocrm/data/upload

  espocrm-daemon:
    image: espocrm/espocrm
    volumes:
     - ./data:/var/www/html
    restart: always
    entrypoint: docker-daemon.sh

volumes:
  espocrm:
```

Thank you.

**Comment by tmachyshyn** [comment]
Hello,

1. All depends on your MySQL server location. Is it on the same machine? If not, you have to make changes in your MySQL server, because by default it allows connection from the localhost only.
2. What is the result of mapping the `./docs:/var/www/html/epsocrm/data/upload`?

**Comment by ValentinPifu** [comment]
1. The MySQL server it's on another server [not on the same one with docker] and I can connect with another docker container to the MySQL. With the config I posted on the first post I should connect to the database or I'm missing something?
2. We use a NFS share which it's on our cluster storage to store all of documents. Now I need to bind it to the upload folder for the EspoCRM.

**Comment by ValentinPifu** [comment]
Hello,

I'm connected to the database and I can see all files, all users, etc.
Users can't connect with the password they know but with the admin user I can connect only with the password in the database not the one in the docker-compose.yml I posted below.

```
version: '3.1'

services:
  espocrm:
    container_name: espocrm
    image: espocrm/espocrm
    environment:
      ESPOCRM_DATABASE_HOST: 192.168.3.107
      ESPOCRM_DATABASE_NAME: crm_v1
      ESPOCRM_DATABASE_USER: crm1
      ESPOCRM_DATABASE_PASSWORD: crm123
      ESPOCRM_ADMIN_USERNAME: admin
      ESPOCRM_ADMIN_PASSWORD: admin
      ESPOCRM_SITE_URL: "http://localhost:8080"
    restart: always
    ports:
      - 8585:80
    volumes:
     - ./data:/var/www/html
     - /home/xxxx/files:/var/www/html/data/upload

  espocrm-daemon:
    image: espocrm/espocrm
    volumes:
     - ./data:/var/www/html
    restart: always
    entrypoint: docker-daemon.sh

volumes:
  espocrm:
```

I'm missing something about the configuration?

Thank you.
