### ISSUE TITLE
Upgrade error from v8.4.2 to v9.1.0

### ISSUE THREAD

**Issue by GitKalle** [espocrm/docker#58]
When the container starts the log shows:

```
crm     | info: Run "upgrade" action.
crm     | info: Start upgrading from version 8.4.2.
crm     | error: Upgrade error, more details:
crm     | Error: SQLSTATE[HY000] [2002] Connection refused
```

My `compose.yml`:

```
services:
  db:
    image: mariadb:11.4
    container_name: crm-db
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: espocrm
      MARIADB_USER: espocrm
      MARIADB_PASSWORD: database_password
    volumes:
      - ./data/mysql:/var/lib/mysql:Z
    restart: always

  espocrm:
    image: espocrm/espocrm:9
    container_name: crm
    depends_on:
      - db
    environment:
      ESPOCRM_DATABASE_PLATFORM: Mysql
      ESPOCRM_DATABASE_HOST: db
      ESPOCRM_DATABASE_USER: espocrm
      ESPOCRM_DATABASE_PASSWORD: database_password
      ESPOCRM_ADMIN_USERNAME: admin
      ESPOCRM_ADMIN_PASSWORD: password
      ESPOCRM_SITE_URL: "http://localhost:8080"
    volumes:
      - ./data/espocrm:/var/www/html:Z
    restart: always
    ports:
      - 8080:80

  espocrm-daemon:
    image: espocrm/espocrm:9
    container_name: crm-daemon
    volumes:
      - ./data/espocrm:/var/www/html:Z
    restart: always
    entrypoint: docker-daemon.sh
```

Can somebody help?
